Add mutex includes where std::unique_lock is used
Fixes build failures due to std::unique_lock being missing:

AnnService/inc/Core/Common/BKTree.h:409:22: error: 'unique_lock' is not a member of 'std'
  409 |                 std::unique_lock<std::shared_timed_mutex> lock(*m_lock);
      |                      ^~~~~~~~~~~

Fixes: https://github.com/microsoft/SPTAG/issues/243